# Generated by Django 3.1.5 on 2021-01-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='user_browser',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='visit',
            name='user_ip',
            field=models.CharField(max_length=1000),
        ),
    ]
