version: "3.3"

services:
  app:
    build: .
    ports:
      - 8000:8000
    environment:
      DB_HOST: 'db'

  db:
    image: postgres:13.1
    environment:
      POSTGRES_DB: 'cloud'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
